### ISSUE TITLE
In this string disparity image file looks same as the image file we have been using ....if that is the case we could have retrived the matrix by using cv::Mat mInL = load_image(imageL, c.gray, c.max_w, c.max_h);why we need to read a file .... and if it doesnt look same then can u tell me how it looks

### ISSUE THREAD

**Issue by ashwarypande** [fwindolf/depth-adaptive-diffusion#11]
https://github.com/fwindolf/depth-adaptive-diffusion/blob/838084aac5b506de1724aed7b780ad2c590d538a/framework/src/image.cu#L234

**Comment by fwindolf** [comment]
No, the file provided by the dataset is not png but pfm. Thus we need another function to open it. The encoding is different. OpenCV cannot open it by default afaik, if you think different and show how, we can use openCV.
