### ISSUE TITLE
why only phi for g=0 is getting initialised not other layers of phi...we have (lamdamax-lamdamin )layers I think

### ISSUE THREAD

**Issue by ashwarypande** [fwindolf/depth-adaptive-diffusion#12]
https://github.com/fwindolf/depth-adaptive-diffusion/blob/838084aac5b506de1724aed7b780ad2c590d538a/framework/src/kernels.cu#L264

**Comment by fwindolf** [comment]
To fulfill the constraint that phi(x, gamma) = [0,1] and phi(x, gamma_min) = 1 and phi(x, gamma_max) = 0 we only need to initialize phi(x, gamma_min) to 1, the rest is set to 0 via Memset. Thus only for g=0 the phi gets set to some value.
