### ISSUE TITLE
And is it necessary to round up values here...what if we keep thems same

### ISSUE THREAD

**Issue by ashwarypande** [fwindolf/depth-adaptive-diffusion#13]
https://github.com/fwindolf/depth-adaptive-diffusion/blob/838084aac5b506de1724aed7b780ad2c590d538a/framework/src/kernels.cu#L416

**Comment by fwindolf** [comment]
I think it was mentioned in the paper (chapter 4.2)

>For  a sub-pixel accurate thresh-old of th=0.5

Try it out and see what happens if we leave it out, then report your results here.
