### ISSUE TITLE
I think check should be a device function or device host fnction because phi is allocated in device or phi should be copied to host variable and then sent through the function...but function anyways afterwards converts device value to host by using memcpy ....but I am not sure if its ok to pass variable whose memeory is allocated in the device to host function

### ISSUE THREAD

**Issue by ashwarypande** [fwindolf/depth-adaptive-diffusion#15]
https://github.com/fwindolf/depth-adaptive-diffusion/blob/838084aac5b506de1724aed7b780ad2c590d538a/framework/main.cu#L199

**Comment by fwindolf** [comment]
This function is just there to have assertions outside the "production" code, so to make sure the constraints hold during debugging. 
We could make it kernel code, but in the end that would fall out again because the function is not needed anymore after the program works as intended.
