### ISSUE TITLE
What do you mean by this ?? why divinding by 5

### ISSUE THREAD

**Issue by ashwarypande** [fwindolf/depth-adaptive-diffusion#18]
https://github.com/fwindolf/depth-adaptive-diffusion/blob/838084aac5b506de1724aed7b780ad2c590d538a/framework/main.cu#L247

**Comment by fwindolf** [comment]
That makes the code in the if clause execute 5 times during the max_iterations iterations. I first had 100 instead of `(c.max_iterations % 5)`, but that made the code slow for many iterations and not execute at all for few iterations.
