### ISSUE TITLE
Where did you get the formula for depth

### ISSUE THREAD

**Issue by ashwarypande** [fwindolf/depth-adaptive-diffusion#19]
https://github.com/fwindolf/depth-adaptive-diffusion/blob/838084aac5b506de1724aed7b780ad2c590d538a/framework/src/kernels.cu#L469

**Comment by fwindolf** [comment]
It can be found in the dataset description of the [Middlebury Stereo 2014 dataset](http://vision.middlebury.edu/stereo/data/scenes2014/)
