### ISSUE TITLE
How can u add the norm of a gradient to (Image_left-Image_right)..What does it represents??

### ISSUE THREAD

**Issue by ashwarypande** [fwindolf/depth-adaptive-diffusion#20]
https://github.com/fwindolf/depth-adaptive-diffusion/blob/838084aac5b506de1724aed7b780ad2c590d538a/framework/src/kernels.cu#L446

**Comment by fwindolf** [comment]
If you look at the paper, the energy is defined as 
![image](https://user-images.githubusercontent.com/10819729/31169372-af3131b8-a8f8-11e7-9086-94993316d2cb.png)

That equals to taking the integral over the whole image for both terms together:
![image](https://user-images.githubusercontent.com/10819729/31169545-444236ee-a8f9-11e7-992d-16e85449e431.png)


For all threads in that block the energy for that pixel (the norm of the gradient plus the value for rho at the calculated gamma) is calculated to a global energy for the whole image.

This is the energy we are trying to minimize and it should decrease until close to zero, where we can stop running our algorithm.

EDIT: the line you marked calculates the rho part of the energy.

**Comment by fwindolf** [comment]
But in fact I just saw that there is a dx and dy that needs to be included in the gradient calculation.

**Comment by fwindolf** [comment]
Not relevant anymore as we use different energy now.
