### ISSUE TITLE
Try out different intializations of Phi

### ISSUE THREAD

**Issue by fwindolf** [fwindolf/depth-adaptive-diffusion#22]
On branch: might-work

Right now phi gets initialized to 1 for gamma_min and 0 for gamma_max (via Memset). Try out different initializations via re-implementing the kernel g_initialize_phi in
https://github.com/fwindolf/depth-adaptive-diffusion/blob/838084aac5b506de1724aed7b780ad2c590d538a/framework/src/kernels.cu#L264

Upload the results here if there are some :)

**Comment by ashwarypande** [comment]
Done..and pushed in might_work_ashwar_random

**Comment by fwindolf** [comment]
Next time please create a new branch from master :)
