### ISSUE TITLE
Implement a consistent dg over all files.

### ISSUE THREAD

**Issue by fwindolf** [fwindolf/depth-adaptive-diffusion#23]
The parameter dg (precision/discretization of g) needs to be consistent over all files in a way that everytime g is applied the result is in pixel coordinates. It might be enough to just add `*dg` in some places. Right now I see:
https://github.com/fwindolf/depth-adaptive-diffusion/blob/838084aac5b506de1724aed7b780ad2c590d538a/framework/src/kernels.cu#L254

https://github.com/fwindolf/depth-adaptive-diffusion/blob/838084aac5b506de1724aed7b780ad2c590d538a/framework/src/kernels.cu#L416

Save the images of the disparities before and after the change and compare them. Post the results here.

**Comment by ashwarypande** [comment]
ok I ll add there

**Comment by ashwarypande** [comment]
You mean to multiply g with d_g everywhere  ? ??

**Comment by fwindolf** [comment]
Think about every occurrence of `g` and if we need pixel coordinates or gamma range there. The places that are pixel coordinates need to be multiplied with `dg`.

**Comment by ashwarypande** [comment]
almost done

**Comment by ashwarypande** [comment]
i pushed 
in d same might_work_ashwar

**Comment by fwindolf** [comment]
Are you sure we don't need the dg in the g_compute_u kernel? That should be pixel coordinates aswell, right?
