### ISSUE TITLE
Check memory/race conditions

### ISSUE THREAD

**Issue by fwindolf** [fwindolf/depth-adaptive-diffusion#24]
Find a parametrization that works and rerun the executable with `cuda-memcheck` and `cuda-memcheck --tool racecheck` or something really close to that.
Use the right executable (`depth-adaptive-diffusion`) and not debug and make sure it compiled with the --lineinfo flag so if there are results the output is meaningful.

**Comment by ashwarypande** [comment]
checked this .....not sure what else to check in this
