### ISSUE TITLE
Track the algorithm using ground-truth initialization

### ISSUE THREAD

**Issue by fwindolf** [fwindolf/depth-adaptive-diffusion#25]
1. Create an very simple, very small image and the ground truth file for the image as a png. 
2. Initialize the algorithm by copying the ground truth disparities to the phi matrix (calculate the values for every layer similar to the implementation here: 
https://github.com/fwindolf/depth-adaptive-diffusion/blob/814342dc6b9ca0f6ecceb9433a849f9bf6890611/framework/main.cu#L201
https://github.com/fwindolf/depth-adaptive-diffusion/blob/814342dc6b9ca0f6ecceb9433a849f9bf6890611/framework/src/kernels.cu#L264
3. Save all necessary images and try to understand what is going on/wrong.
4. Create gifs with the python file that i'll attach.
5. Show the results here.

**Comment by fwindolf** [comment]
Run the python file with python 3 and arguments `-i <folder with images>`
[make_gif.py.zip](https://github.com/fwindolf/depth-adaptive-diffusion/files/1356386/make_gif.py.zip)

**Comment by fwindolf** [comment]
Divide among yourself who wants to do that please :)

**Comment by ashwarypande** [comment]
working on this

**Comment by ashwarypande** [comment]
done
