### ISSUE TITLE
Reimplement the energy calculation 

### ISSUE THREAD

**Issue by fwindolf** [fwindolf/depth-adaptive-diffusion#26]
Use the lifted energy formulation to compute the energy that we try to minimize.
![image](https://user-images.githubusercontent.com/10819729/31183123-fed48ba2-a925-11e7-984c-dff636c055b0.png)

Try to reuse the gradient of phi, rho to compute it. I can imagine the kernel to look something like this:
`__global__ void g_compute_energy(float * Grad3_Phi, float *Phi, float *Rho, float * energy, int w, int h, int nc, float lambda)`

The sigma indicates that we need to do this for all gamma layers and for every point in the 'image'.
The gradient in gamma-direction should be implemented via forward differences (don't forget dg).

**Comment by ashwarypande** [comment]
Done

**Comment by fwindolf** [comment]
Nice, now you only need to push it on some branch so i can merge it. Maybe you can create a pull request?

**Comment by ashwarypande** [comment]
i cant push 
its asking for username and password as u have not given me rights in this project 'https://svncvpr.in.tum.de':

**Comment by fwindolf** [comment]
Still unable to push?

**Comment by ashwarypande** [comment]
i already pushed it

**Comment by fwindolf** [comment]
Can u push it in a way that the structure of the project is kept? 
You created new files in the project directory which makes it impossible to merge your branch into master/might-work.

**Comment by ashwarypande** [comment]
ok .. i did that

[3:48 PM, 10/5/2017] +49 1575 2189132: Energy is behaving in a bit shitty way
[3:48 PM, 10/5/2017] +49 1575 2189132: Its increasing decreasing
[3:51 PM, 10/5/2017] +49 1575 2189132: try to run till 1000 iterations in the code i committed in git
[3:55 PM, 10/5/2017] +49 1575 2189132: if u run for more iterations energy is decreasing then

**Comment by fwindolf** [comment]
Did you push it? I still only see new files and no changes.

As we use the lifted energy function it should continuously decrease if i understood that correctly. But I guess that's because of the bug that there still is somewhere. I'll look at the implementation after u pushed it but I'd suggest u work on  #23 right now and see if that fixes it.

**Comment by ashwarypande** [comment]
but i pushed check new branch might_work_ashwa

**Comment by ashwarypande** [comment]
ok i ll work on 23

**Comment by fwindolf** [comment]
alright do me a favor and maybe prefix your branches with the issue youre working on :)
so 23_... for the next one.

**Comment by ashwarypande** [comment]
ok

**Comment by ashwarypande** [comment]
now its decreasing everything is right now

**Comment by ashwarypande** [comment]
![image](https://user-images.githubusercontent.com/16420753/31232464-395ebf58-a9ea-11e7-96ef-8aee401433e8.png)

**Comment by ashwarypande** [comment]
I think this has negative values Grad3_Phi

**Comment by fwindolf** [comment]
I can tell u for sure that gamma ranging from -16 to 16 is insufficient. Other than that I'm not really sure what you mean.
I've corrected the format and reused the gradient instead of calculating it again. Also I've moved the calculation of U out of the loop because we don't use it anymore with the new energy function. 
I'm going to merge this into might-work now.

**Comment by ashwarypande** [comment]
I meant it was working properly
because it was decreasing
