### ISSUE TITLE
It should be assigned zero when statement is not true

### ISSUE THREAD

**Issue by ashwarypande** [fwindolf/depth-adaptive-diffusion#3]
https://github.com/fwindolf/depth-adaptive-diffusion/blob/838084aac5b506de1724aed7b780ad2c590d538a/framework/src/kernels.cu#L397

**Comment by fwindolf** [comment]
If g == 0, the neumann boundaries would make it p3 - p3 which is zero. As we add div3 up, plus 0 doesnt change anything.

**Comment by fwindolf** [comment]
@ashwarypande what is your question?
