### ISSUE TITLE
normalize seems to mess up the dimensions

### ISSUE THREAD

**Issue by fwindolf** [fwindolf/depth-adaptive-diffusion#32]
The function normalize corrupts the dimensions somehow:
https://github.com/fwindolf/depth-adaptive-diffusion/blob/a016388f925fd25cb801c40943512f906bb1edeb/framework/src/reduce.cu#L77

**Comment by ashwarypande** [comment]
I am working now on the normalizer...cheers

**Comment by ashwarypande** [comment]
I couldn't find any bug ..It gives values between 0 and 1 .. I even printed them. If you want me to have complete new implementation of that I can do that

**Comment by fwindolf** [comment]
Nah if it works it works. But it messes up the dimensions of the image somehow, right?

**Comment by ashwarypande** [comment]
done
