### ISSUE TITLE
SegFault

### ISSUE THREAD

**Issue by fwindolf** [fwindolf/depth-adaptive-diffusion#37]
./depth_adaptive_diffusion -image ../images/Motorcycle-perfect/im -gamma-min -10 -gamma_max 30 -lambda 100 -w 2000 -iterations 10000 -dg 8f -focal_plane 0.3 -radius 1.5f leads to a segmentation fault during the diffusion.

**Comment by ashwarypande** [comment]
I am not getting segmentation fault but out of memory

**Comment by fwindolf** [comment]
Yeah seems like -w 2000 is just way too big.
