### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by fwindolf** [fwindolf/depth-adaptive-diffusion#38]
What do you guys think about this as an outline:

- Introduction to stereo vision (1m)
Camera setup
Disparities 
- Isikawas approach (1m)
Pitfalls (memory) 
Graph cuts (min cut max flow)
- Variational approach (3m)
Explanation of data term/regularizer
Functional lifting idea
Primal dual algorithm (gif of phi)
Energy (gif of rho)
- Diffusion (2m)
Explanation of field of view 
Creation of G matrix from depth values 
- Implementation (2m)
2 steps (disparities, then diffusion)
- Pitfalls (1m)
Computation of rho
Consistency between gamma range/pixel coordinates
- Outlook (2m)
Possible optimizations (maybe run the profiler to see bottlenecks)
Reduce memory consumption (eg images->texture)
- Demo (3m)
Compare ground truth disparities with our results
Show images for different focal planes
Show influence of parameters (gamma_min/gamma_max)

= 15m speaking time

**Comment by ashwarypande** [comment]
sounds good
