### ISSUE TITLE
if here both in x and y direction the image need to be downsampled...then the variabe will be overwritten

### ISSUE THREAD

**Issue by ashwarypande** [fwindolf/depth-adaptive-diffusion#4]
https://github.com/fwindolf/depth-adaptive-diffusion/blob/838084aac5b506de1724aed7b780ad2c590d538a/framework/src/image.cu#L117

**Comment by ashwarypande** [comment]
check this

**Comment by ashwarypande** [comment]
factor will be overwritten each time

**Comment by fwindolf** [comment]
That is so it keeps the original ration of w to h.
