### ISSUE TITLE
And here size should be output image size , I think so should be multiplied by the factor as size() function will give the size of input image before desampling..if I am correct

### ISSUE THREAD

**Issue by ashwarypande** [fwindolf/depth-adaptive-diffusion#7]
https://github.com/fwindolf/depth-adaptive-diffusion/blob/aa5dc78833e3776b9bf7a3bac172976ce77d713f/framework/src/image.cu#L128

**Comment by fwindolf** [comment]
Size() is just like NULL in this case, it is needed as a parameter but does not change anything, see:
http://docs.opencv.org/2.4/modules/imgproc/doc/geometric_transformations.html?highlight=resize#cv2.resize
