### ISSUE TITLE
why 3 here ...number of disparities I think range from (gammmax-gammamin) or is it for number of channels

### ISSUE THREAD

**Issue by ashwarypande** [fwindolf/depth-adaptive-diffusion#9]
https://github.com/fwindolf/depth-adaptive-diffusion/blob/838084aac5b506de1724aed7b780ad2c590d538a/framework/src/image.cu#L245

**Comment by fwindolf** [comment]
The image has disparities as brightness values in pfm. So we load a single channel image here, just like the U we produce.
